---
    - name: Run openrc file
      template: src=../template/admin-openrc.sh.j2 dest=~/admin-openrc
    - name: Create keypair
      os_keypair:
        name: mykey
        auth_type: password
        state: present
      register: key

