---
    - name: Run openrc file
      template: src= admin-openrc.sh.j2 dest=~/admin-openrc
    - name: Create Volume
      os_volume:
        state: present
        cloud: mycloud
        display_name: test_volume
        size: 1
        availability_zone: nova
        display_description: Test volume created by Ansible.
