---
- hosts: localhost
  become: true
  roles:
    - opks
  vars: 
    - vars_prompt
  tasks:
    - include: image.yml
    - include: flavor.yml
    - include: keypair.yml
    - include: volume.yml
    - include: project.yml
    - include: instance.yml
     
